
development:
  icc_app_code: <%= ENV['JPOS_ICC_APP_CODE'] %>
  aliyun_sms_access_key_secret: <%= ENV['JPOS_SMS_ACCESS_KEY_SECRET'] %>
  aliyun_sms_access_key_id: <%= ENV['JPOS_SMS_ACCESS_KEY_ID'] %>
  aliyun_sms_sign_name: <%= ENV['JPOS_SMS_SIGN_NAME'] %>
  aliyun_sms_template_code_verification: SMS_144151564
  aliyun_sms_template_send_password: SMS_151772113
  wx_url: 'http://testwx.getstore.cn'
production:
  icc_app_code: <%= ENV['JPOS_ICC_APP_CODE'] %>
  aliyun_sms_access_key_secret: <%= ENV['JPOS_SMS_ACCESS_KEY_SECRET'] %>
  aliyun_sms_access_key_id: <%= ENV['JPOS_SMS_ACCESS_KEY_ID'] %>
  aliyun_sms_sign_name: <%= ENV['JPOS_SMS_SIGN_NAME'] %>
  aliyun_sms_template_code_verification: SMS_146804242
  aliyun_sms_template_send_password: SMS_151772113
  wx_url: 'http://wx.wyfpj.com'
