default: &default
#  corpid: "corpid"
#  corpsecret: "corpsecret"
#  agentid:  1
# Or if using public account, only need above two line
  appid: "wxe1e41bc95e1ffc98" #"wx617b20b7ded64c67"
  secret: "5ed88d0faa88ba705a31e650791c5d85" #"62ae0895b20b632a6db319450b215be7"
  token: "mytoken"
  access_token: "tmp/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "my_encoding_aes_key"
  jsapi_ticket: "tmp/wechat_jsapi_ticket"
  api_ticket: "tmp/wechat_api_ticket"

production:
  appid: <%= ENV['JPOS_WECHAT_APPID'] %>
  secret: <%= ENV['JPOS_WECHAT_SECRET'] %>
  token:    <%= ENV['JPOS_WECHAT_TOKEN'] %>
  access_token: "tmp/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  <%= ENV['WECHAT_ENCODING_AES_KEY'] %>
  jsapi_ticket: "tmp/wechat_jsapi_ticket"
  api_ticket: "tmp/wechat_api_ticket"
#  corpid:     <%= ENV['WECHAT_CORPID'] %>
#  corpsecret: <%= ENV['WECHAT_CORPSECRET'] %>
#  agentid:    <%= ENV['WECHAT_AGENTID'] %>
## Or if using public account, only need above two line
##  appid:
##  secret:
#  token:      <%= ENV['WECHAT_TOKEN'] %>
#  timeout:    30,
#  skip_verify_ssl: true
#  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>
#  encrypt_mode: false # if true must fill encoding_aes_key
#  encoding_aes_key:  <%= ENV['WECHAT_ENCODING_AES_KEY'] %>
#  jsapi_ticket: <%= ENV['WECHAT_JSAPI_TICKET'] %>
#  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds
  trusted_domain_fullname: "http://wxauth2.wechatmore.getstore.cn/rlcar"

development:
  <<: *default
  trusted_domain_fullname: "http://testwx.getstore.cn"

  appid: "wx617b20b7ded64c67" #getstore-tester
  secret: "62ae0895b20b632a6db319450b215be7"

test:
  <<: *default
