new_order_created:
  template_id: "Tbs485ygKHXrfuR_-8v416YmZjz1jrN4uY9NuZY4xRM"
  url: "http://weixin.qq.com/download"
  topcolor: "#FF0000"
  data:
    first:
      value: "订单生成通知"
      color: "#0A0A0A"
    keyword1:
      value: "2014年7月21日 18:36"
      color: "#CCCCCC"
    keyword2:
      value: "苹果"
      color: "#CCCCCC"
    keyword3:
      value: "007"
      color: "#CCCCCC"
    remark:
      value: "订单成功"
      color: "#173177"
